import type {} from "@netlify/functions";
import {captureFields,signatureValid,secretValid,text,applyIncoming,CRMError,type Incoming} from './_shared/crm-domain';
import {mutate,fail} from './_shared/crm-store';
type MetaMessage={id?:string;from?:string;type?:string;text?:{body?:string};button?:{text?:string};interactive?:{button_reply?:{title?:string};list_reply?:{title?:string}}};
type MetaValue={leadgen_id?:string;page_id?:string;form_id?:string;ad_id?:string;metadata?:{phone_number_id?:string};contacts?:{wa_id?:string;profile?:{name?:string}}[];messages?:MetaMessage[]};
export default async function handler(req:Request){try{
 const secret=Netlify.env.get('CRM_META_APP_SECRET');const verify=Netlify.env.get('CRM_META_VERIFY_TOKEN');if(!secret||!verify)throw new CRMError('Meta integration is not configured.',503);
 if(req.method==='GET'){const q=new URL(req.url).searchParams;if(q.get('hub.mode')==='subscribe'&&secretValid(q.get('hub.verify_token'),verify))return new Response(q.get('hub.challenge')||'');throw new CRMError('Verification failed.',403);}
 if(req.method!=='POST')return new Response('Method not allowed',{status:405});const raw=await req.text();if(raw.length>1000000)throw new CRMError('Payload too large.',413);if(!signatureValid(raw,req.headers.get('x-hub-signature-256'),secret))throw new CRMError('Invalid signature.',401);
 let payload;try{payload=JSON.parse(raw);}catch{throw new CRMError('Invalid JSON.');}if(!Array.isArray(payload.entry))throw new CRMError('Invalid event payload.');
 const incoming:Incoming[]=[];
 for(const entry of payload.entry){for(const change of entry.changes||[]){const v:MetaValue=change.value||{};
 if(payload.object==='page'&&change.field==='leadgen'&&v.leadgen_id){const token=Netlify.env.get('CRM_META_PAGE_TOKEN'),version=Netlify.env.get('CRM_META_GRAPH_VERSION'),pageId=Netlify.env.get('CRM_META_PAGE_ID');if(!token||!version||!pageId)throw new CRMError('Lead Ads retrieval is not configured.',503);if(String(entry.id)!==pageId||String(v.page_id)!==pageId)throw new CRMError('Page is not authorised.',403);if(!/^\d+$/.test(v.leadgen_id)||!/^v\d+\.\d+$/.test(version))throw new CRMError('Invalid Meta API configuration.');const response=await fetch(`https://graph.facebook.com/${version}/${v.leadgen_id}?fields=field_data,created_time`,{headers:{Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(12000)});if(!response.ok)throw new CRMError('Meta lead retrieval failed. Retry delivery after checking permissions.',503);const lead=await response.json();const fields:Record<string,string>=Object.fromEntries((lead.field_data||[]).map((f:{name:string;values:string[]})=>[f.name,f.values?.[0]||'']));incoming.push({fields:captureFields(Object.fromEntries((lead.field_data||[]).map((f:{name:string;values:string[]})=>[f.name,f.values]))),eventId:`meta:${v.leadgen_id}`,source:'Meta Ads',name:fields.full_name||[fields.first_name,fields.last_name].filter(Boolean).join(' ')||'Meta enquiry',email:fields.email,phone:fields.phone_number,company:fields.company_name,program:fields.program||fields.course||fields.programme,message:`Meta Lead Ads enquiry\nForm: ${v.form_id||'Unknown'} · Ad: ${v.ad_id||'Unknown'}\n${Object.entries(fields).map(([k,v])=>`${k}: ${v}`).join('\n')}`});}
 if(payload.object==='whatsapp_business_account'&&change.field==='messages'&&v.messages?.length){const phoneId=Netlify.env.get('CRM_WHATSAPP_PHONE_ID');if(!phoneId)throw new CRMError('WhatsApp integration is not configured.',503);if(v.metadata?.phone_number_id!==phoneId)throw new CRMError('Phone number is not authorised.',403);for(const m of v.messages){if(!m.id||!m.from)throw new CRMError('Invalid WhatsApp message.');incoming.push({eventId:`whatsapp:${m.id}`,source:'WhatsApp',name:v.contacts?.find(c=>c.wa_id===m.from)?.profile?.name||`WhatsApp ${m.from}`,phone:`+${m.from}`,message:text(m.text?.body||m.button?.text||m.interactive?.button_reply?.title||m.interactive?.list_reply?.title||`Incoming ${m.type||'media'} message. View the attachment in WhatsApp Business.`,5000)});}}
 }}
 if(incoming.length>100)throw new CRMError('Too many events.',413);await mutate(state=>incoming.map(i=>applyIncoming(state,i)));return Response.json({received:true});
 }catch(error){return fail(error);}};
