// Snapshot of https://etiworld.ae/programs and /corporate-training, verified 2026-10-02.
export const programs: string[] = [
  "Certified Management Accountant (CMA)",
  "Certified Procurement International Manager (CPIM)",
  "Certified Procurement International Professional (CPIP)",
  "Certified International Supply Chain Professional (CISP)",
  "Certified International Supply Chain Manager (CISM)",
  "UAE VAT (Value Added Tax) Training",
  "UAE E-Invoicing Compliance Training",
  "Sales Professional with AI Course",
  "MLRO (Money Laundering Reporting Officer) Training",
  "Letter of Credit (LC) Training",
  "Hotel and Hospitality Management",
  "Export and Import Management Course",
  "Executive Secretary / Office Administrator Training",
  "AML Compliance CPD Programme for Exchange Houses",
  "Certified Human Resource Professional (CHRP)",
  "Certified Quantity Surveyor Training",
  "Professional Certificate in Supply Chain & Operations Management - CILT Level 5 (UK)",
  "Airline Cabin Crew Training Course",
  "Public Speaking, Presentation Skills & Professional Communication",
  "FIDIC Contracts Management",
  "Certified Freight Forwarding Professional (CFFP)",
  "Certified Anti-Money Laundering Specialist (CAMS)",
  "Certified Human Resource Manager (CHRM)",
  "Human Resource Management with PRO & UAE Labour Law",
  "UAE Labour & Immigration Law",
  "UAE Corporate Tax Training",
  "Logistics & Supply Chain Management",
  "Document Control Training",
  "Diploma in International Financial Reporting (DipIFR) — ACCA",
  "Certificate in International Financial Reporting (CertIFR) — ACCA",
  "AI Prompt Engineering Course",
  "AI Generalist Course",
  "Certified Accounting Professional",
  "GRC Professional Training",
  "Microsoft Power BI Training",
  "PMP (Project Management Professional) Training",
  "IELTS Academic & General Training",
  "Facility Management Training",
  "Airport Terminal and Ramp Ground Handling Services Training",
  "Airport Ramp Services Course",
  "Airport Terminal Ground Handling",
  "Airport Passenger Ground Services",
  "Foundation in Travel & Tourism Diploma",
  "Compliance for Virtual Asset Businesses",
  "Compliance for UAE Trading Companies",
  "Compliance for Trust & Company Service Providers",
  "Compliance for Payment Services & FinTech",
  "Compliance for Legal Consultants & Law Firms",
  "Compliance for the Insurance Sector",
  "Compliance for Independent Accountants & Auditors",
  "Compliance for Dealers in Precious Metals & Stones",
  "Compliance for the UAE Real Estate Sector",
  "Compliance for Banks & Financial Institutions",
  "AML Compliance Training",
  "Certified Internal Auditor (CIA) Exam Preparation",
  "PRO Training"
];
export const corporateCategories: string[] = [
  "Leadership & Management",
  "Human Resources",
  "AI - Artificial Intelligence",
  "Skills Development",
  "Finance & Compliance",
  "Microsoft & IT Skills",
  "Customer Service, Sales & Marketing",
  "Procurement & Contracts",
  "Aviation, Hospitality & Tourism",
  "Quality Management & Process Improvement",
  "Team Building"
];
