'use client';
import {useState,type FormEvent} from 'react';
import type {Lead} from './model';
export default function LeadFollowUps({lead,disabled,author,onSave}:{lead:Lead;disabled:boolean;author:string;onSave:(lead:Lead)=>Promise<void>}){
 const [due,setDue]=useState(''),[remark,setRemark]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const history=[...(lead.followUps||[])];
 if(lead.followUpAt&&!history.some(f=>f.due===lead.followUpAt))history.unshift({id:'legacy',due:lead.followUpAt,remark:'Previously scheduled follow-up',at:lead.updatedAt,author:'CRM'});
 async function submit(e:FormEvent){e.preventDefault();if(disabled||saving)return;setSaving(true);setError('');try{const date=new Date(due).toISOString();await onSave({...lead,followUpAt:date,followUps:[{id:crypto.randomUUID(),due:date,remark:remark.trim(),at:new Date().toISOString(),author},...(lead.followUps||[])]});setDue('');setRemark('');}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 return <div className="crm-detail-section"><h3>Follow-ups & remarks</h3><p><strong>Next follow-up: </strong>{lead.followUpAt?new Date(lead.followUpAt).toLocaleString():'Not scheduled'}</p><form onSubmit={submit}><label>Next follow-up date and time<input aria-label="Next follow-up date and time" required type="datetime-local" value={due} disabled={disabled||saving} onChange={e=>setDue(e.target.value)}/></label><label>Follow-up remarks<textarea aria-label="Follow-up remarks" maxLength={5000} value={remark} disabled={disabled||saving} onChange={e=>setRemark(e.target.value)} placeholder="Conversation, outcome and next steps…"/></label><small>Times: {Intl.DateTimeFormat().resolvedOptions().timeZone}. Adding an entry updates the next reminder and keeps previous follow-ups below.</small><button className="crm-btn primary" disabled={disabled||saving}>{saving?'Saving…':'Add follow-up'}</button></form>{lead.followUpAt&&<button className="crm-text-btn" disabled={disabled||saving} onClick={async()=>{setSaving(true);setError('');try{await onSave({...lead,followUpAt:''});}catch(e){setError((e as Error).message);}finally{setSaving(false);}}}>Clear next reminder (keep history)</button>}{error&&<p role="alert">{error}</p>}<h3>Follow-up history ({history.length})</h3>{!history.length&&<p>No follow-ups recorded yet.</p>}<div className="crm-timeline">{history.map(f=><article key={f.id}><i/><div><strong>{new Date(f.due).toLocaleString()}</strong><p style={{whiteSpace:'pre-wrap'}}>{f.remark||'No remarks added.'}</p><small>{f.author}{f.at&&Number.isFinite(Date.parse(f.at))?` · Added ${new Date(f.at).toLocaleString()}`:''}</small></div></article>)}</div><h3>All notes & remarks ({lead.notes.length})</h3><div className="crm-timeline">{lead.notes.map(n=><article key={n.id}><i/><div><small>{n.author} · {new Date(n.at).toLocaleString()}</small><p style={{whiteSpace:'pre-wrap'}}>{n.text}</p></div></article>)}</div></div>;
}
