import type {Lead,TeamMember} from './model';
import {money} from './model';
export function salespersonPipeline(leads:Lead[],members:Pick<TeamMember,'id'|'name'>[],live:boolean,metric:'pipeline'|'revenue'='pipeline'){
 return members.map(member=>{const open=leads.filter(l=>(metric==='revenue'?l.stage==='Enrolled':!['Enrolled','Lost'].includes(l.stage))&&(live?l.ownerId===member.id:l.ownerId?l.ownerId===member.id:l.owner===member.name));const corporate=open.filter(l=>l.leadType==='corporate');return {id:member.id,name:member.name,count:open.length,value:open.reduce((sum,l)=>sum+l.value,0),corporate:corporate.length,individual:open.length-corporate.length};});
}
export default function SalesPipeline({leads,team,actor,isAdmin,live,period,metric='pipeline'}:{leads:Lead[];team:TeamMember[];actor:{id:string;name:string}|null;isAdmin:boolean;live:boolean;period:string;metric?:'pipeline'|'revenue'}){
 const members=isAdmin?team.filter(m=>m.role==='sales'):actor?[actor]:[];
 const rows=salespersonPipeline(isAdmin?leads:leads.filter(l=>l.ownerId===actor?.id),members,live,metric);
 const maximum=Math.max(1,...rows.map(r=>r.value));
 return <section className="crm-panel crm-sales-pipeline"><div className="crm-panel-head"><div><h2>{metric==='revenue'?(isAdmin?'Enrolment revenue by salesperson':'My enrolment revenue'):(isAdmin?'Open pipeline by salesperson':'My open pipeline')}</h2><p>Individual and corporate {metric==='revenue'?'enrolments':'opportunities'} · {period} by lead creation date · {metric==='revenue'?'Enrolled deal value':'Excludes Enrolled and Lost'}</p></div></div><div className="crm-sales-pipeline-grid">{rows.map(row=><article key={row.id}><h3>{row.name}</h3><strong>AED {money(row.value)}</strong><p>{row.count} {metric==='revenue'?`successful enrolment${row.count===1?'':'s'}`:`open opportunit${row.count===1?'y':'ies'}`}</p><div className="crm-sales-pipeline-bar" aria-hidden="true"><span style={{width:`${row.value/maximum*100}%`}}/></div><small>{row.individual} individual · {row.corporate} corporate</small></article>)}</div>{!rows.length&&<p className="crm-pipeline-empty">No salesperson records available.</p>}{isAdmin&&<p className="crm-pipeline-empty">Unassigned leads and leads owned by super admins are included in the overall {metric==='revenue'?'Enrolment Revenue':'Open Pipeline'} total above, but not in these salesperson totals.</p>}{metric==='revenue'&&<p className="crm-pipeline-empty">Revenue represents enrolled deal values, not payments collected.</p>}</section>;
}
