'use client';
import {useEffect,useState} from 'react';
import {readBackend,runCommand} from './backend';
import TargetChart from './TargetChart';
import {targetStatus} from './target-status';
type Row={staffId:string;name:string;email:string;status:string;target:number|null;version:string;achieved:number;percentage:number|null;remaining:number|null;undatedEnrolments:number};
type Progress={month:string;daysRemaining:number;rows:Row[]};
const money=(n:number)=>new Intl.NumberFormat('en-AE',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
const currentMonth=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dubai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()).slice(0,7);
function TargetInput({row,month,onSaved}:{row:Row;month:string;onSaved:()=>Promise<void>}){
 const [amount,setAmount]=useState(String(row.target??'')),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 return <form className="crm-target-input" onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{await runCommand({action:'target.set',staffId:row.staffId,month,amount:Number(amount),version:row.version});await onSaved();setMessage('Saved');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}><input aria-label={`Monthly target for ${row.name}`} type="number" required min="0" max="1000000000" step="0.01" placeholder="Target AED" value={amount} disabled={busy} onChange={e=>setAmount(e.target.value)}/><button className="crm-btn primary" disabled={busy}>{busy?'Saving…':'Save target'}</button>{message&&<small role="status">{message}</small>}</form>;
}
export default function SalesTargets({isAdmin,live,compact=false}:{isAdmin:boolean;live:boolean;compact?:boolean}){
 const [month,setMonth]=useState(currentMonth),[data,setData]=useState<Progress|null>(null),[error,setError]=useState('');
 async function refresh(){if(!live)return;const result=await readBackend(`view=targets&month=${encodeURIComponent(month)}`);setData(result);setError('');}
 useEffect(()=>{let cancelled=false;setData(null);setError('');const load=async()=>{if(!live)return;try{const result=await readBackend(`view=targets&month=${encodeURIComponent(month)}`);if(!cancelled){setData(result);setError('');}}catch(e){if(!cancelled)setError((e as Error).message);}};void load();const timer=setInterval(()=>void load(),60000);return()=>{cancelled=true;clearInterval(timer);};},[month,live]);
 return <section className="crm-panel crm-sales-targets"><div className="crm-panel-head"><div><h2>{isAdmin?'Monthly sales targets':'My monthly sales target'}</h2><p>Calendar months · UAE time · {data?.daysRemaining??'—'} days remaining (including today)</p></div><label>Month<input aria-label="Target calendar month" type="month" min="2000-01" max="2099-12" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></label></div><p className="crm-target-explanation">Achievement is the value of currently assigned leads marked Enrolled in this month, including individual and corporate leads. Values represent sales booked, not payments collected.</p>{!live?<p>Sign in to view or set real monthly targets.</p>:error?<p role="alert">{error} <button className="crm-text-btn" onClick={()=>void refresh().catch(e=>setError(e.message))}>Retry</button></p>:!data?<p>Loading targets…</p>:<><div className="crm-target-cards">{data.rows.map(row=><article key={row.staffId}><h3>{row.name}</h3>{isAdmin&&<small>{row.email} · {row.status}</small>}<TargetChart row={row} max={Math.max(1,...data.rows.flatMap(r=>[r.target||0,r.achieved]))}/><dl><div><dt>Monthly target</dt><dd style={{color:row.target===null?undefined:'#946200'}}>{row.target===null?'Not set':`AED ${money(row.target)}`}</dd></div><div><dt>Achieved</dt><dd style={{color:targetStatus(row.target,row.achieved).color}}>AED {money(row.achieved)}</dd></div><div><dt>Achieved percentage</dt><dd style={{color:targetStatus(row.target,row.achieved).color}}>{row.percentage===null?'—':`${row.percentage.toFixed(1)}%`}</dd></div><div><dt>{targetStatus(row.target,row.achieved).label}</dt><dd style={{color:targetStatus(row.target,row.achieved).color}}>{row.target===null?'—':`AED ${money(Math.abs(targetStatus(row.target,row.achieved).difference))}`}</dd></div><div><dt>Days remaining</dt><dd>{data.daysRemaining}</dd></div></dl>{row.percentage!==null&&<progress style={{accentColor:targetStatus(row.target,row.achieved).color}} aria-label={`${row.name} target progress`} max={100} value={Math.min(100,row.percentage)}/>} {!!row.undatedEnrolments&&<p>{row.undatedEnrolments} older enrolled lead(s) have no recorded enrolment date and are excluded from monthly achievement.</p>}{isAdmin&&!compact&&<TargetInput key={`${month}:${row.staffId}:${row.version}`} row={row} month={month} onSaved={refresh}/>}</article>)}</div>{!data.rows.length&&<p>No salesperson accounts found. Add sales staff in Team first.</p>}{isAdmin&&compact&&<p>Open Sales targets to set each salesperson’s monthly amount.</p>}</>}</section>;
}
