import {SiteFooter,SiteHeader} from "../components";

const articles=[
  {category:"Leadership",title:"The shift from managing work to leading performance",excerpt:"Four practical changes that help managers create clarity, ownership and stronger team momentum.",image:"/images/course-leadership.png",read:"6 min read"},
  {category:"Professional Excellence",title:"Executive presence begins before you enter the room",excerpt:"How preparation, judgement and communication combine to create professional credibility.",image:"/images/course-professional-excellence.png",read:"5 min read"},
  {category:"Procurement",title:"Strategic sourcing is a business conversation",excerpt:"Moving procurement beyond price to value, resilience, supplier capability and shared outcomes.",image:"/images/course-cpip.png",read:"7 min read"},
  {category:"Finance",title:"Turning management accounting into better decisions",excerpt:"Why useful financial insight connects performance data with the decisions leaders need to make.",image:"/images/course-cma.png",read:"6 min read"},
  {category:"Learning & Development",title:"What makes corporate learning transfer to work?",excerpt:"Design principles that help new capability survive beyond the training room.",image:"/images/corporate-training-hero.png",read:"8 min read"},
  {category:"Entrepreneurship",title:"A resilient business model starts with sharper questions",excerpt:"A practical lens for testing customer value, resources, economics and execution risk.",image:"/images/course-entrepreneurship.png",read:"5 min read"}
];

export default function Blog(){const featured=articles[0];return <main><SiteHeader/><section className="blog-hero blog-hero-background"><div className="blog-hero-copy"><div className="section-kicker light">Entrepôt Insights</div><h1>Ideas for people<br/>who keep <em>growing.</em></h1><p>Practical perspectives on leadership, professional capability and the changing world of work.</p></div></section><section className="featured-article section-pad"><div className="featured-image"><img src={featured.image} alt="Leadership team in discussion"/></div><div><span>{featured.category} · {featured.read}</span><h2>{featured.title}</h2><p>{featured.excerpt}</p><strong>Featured insight</strong></div></section><section className="blog-list section-pad"><div className="blog-list-head"><div className="section-kicker">Latest thinking</div><h2>Explore our insights.</h2></div><div className="blog-grid">{articles.slice(1).map((a,i)=><article key={a.title}><div className="blog-card-image"><img src={a.image} alt="" loading="lazy"/></div><div className="blog-card-copy"><span>{a.category} · {a.read}</span><h3>{a.title}</h3><p>{a.excerpt}</p><small>Insight {String(i+2).padStart(2,"0")}</small></div></article>)}</div></section><section className="blog-cta"><div><span>Stay curious</span><h2>Learning continues between programmes.</h2></div><div><p>Talk to our team about the programmes and perspectives most relevant to your professional goals.</p><a className="btn-gold" href="mailto:courses@entrepot.ae?subject=Entrepot Insights">Email courses@entrepot.ae <span>↗</span></a></div></section><SiteFooter/></main>}
