import Link from "next/link";
import {SiteFooter,SiteHeader} from "../components";
import CorporateLeadForm from "./CorporateLeadForm";
import courseData from "./course-data.json";

const categories=[
  {no:"01",title:"Leadership & Management",courses:["Emotional Intelligence for Leaders · 2 days","Transformational Leadership · 5 days","Masterclass in Leadership Thinking · 5 days","Advanced Leadership Skills · 3 days","Change Management Masterclass · 2 days","Artificial Intelligence for Leaders · 1 day","Smart Management Skills · 2 days","Building High-Performance Teams · 2 days","Strategic Office Management & Leadership Excellence · 2 days"]},
  {no:"02",title:"Human Resources",courses:["UAE Labor & Employment Law · 2 days","KSA Labor & Employment Law · 2 days","KPI & Balanced Scorecard · 2 days","AI for HR · 1 day","Certified Train the Trainer · 3 days","People Analytics for HR · 1 day","Diversity, Equity & Inclusion Masterclass · 2 days","Performance Management Specialist · 2 days","Talent Management Essential Skills · 2 days","Talent Development Essential Skills · 2 days","Certified Human Resource Professional (CHRP) · 3 days","Certified Human Resource Manager (CHRM) · 3 days","Performance Appraisal & Feedback Skills · 2 days"]},
  {no:"03",title:"AI - Artificial Intelligence",courses:["Generative AI for Workplace Productivity · 1 day","AI for Leaders · 1 day","AI for HR · 1 day","AI-Powered Sales · 1 day","AI for Procurement · 1 day","AI for Aviation · 1 day","AI for Supply Chain Professionals · 1 day","Certified Artificial Intelligence Practitioner · 1 day","AI for Data Analytics & Decision Making · 1 day","AI-Powered Project Management · 1 day"]},
  {no:"04",title:"Skills Development",courses:["Emotional Intelligence Workshop · 2 days","Problem Solving & Decision Making · 2 days","Effective Communication Skills - Influence & Impact · 2 days","Creative Thinking & Innovation at Workplace · 3 days","Train the Trainer · 3 days","Effective Feedback Skills · 2 days","Time & Task Management Skills · 2 days","Interpersonal Skills & Effective Communication · 2 days","Storytelling & Effective Presentation Skills · 1 day","Build Trusting Teams · 2 days","Administrative Skills Workshop · 2 days","Perform Better under Pressure: Resilience, Confidence & Perseverance · 2 days"]},
  {no:"05",title:"Finance & Compliance",courses:["Finance for Non-Finance Professionals · 3 days","UAE Corporate Tax & Strategic Planning · 2 days","Anti-Money Laundering (AML) · 1 day","Power BI for Data Analysis & Reporting · 2 days","Artificial Intelligence in Finance · 1 day"]},
  {no:"06",title:"Microsoft & IT Skills",courses:["Basic Excel · 1 day","Advanced Excel - Functions, Power Query & Power Pivots · 2 days","Excel for HR & Admin Professionals · 1 day","Power BI for Data Analysis, Reporting & Decision Making · 2 days","Mastering Power BI · 2 days","Microsoft Office 365 Training · 2 days","Cybersecurity Essentials Workshop · 1 day","Ethical Hacking · 2 days"]},
  {no:"07",title:"Customer Service, Sales & Marketing",courses:["Customer Service Excellence · 2 days","Service Excellence for Frontline Professionals · 1 day","Professional Telephone & Email Etiquette · 1 day","Sales Excellence Programme · 1 day","Consultative Selling Techniques · 2 days","Sales Leadership Excellence · 2 days","Cross-Selling & Upselling Strategies · 1 day","Digital Marketing Essentials · 4 days","AI in Sales & Marketing · 1 day"]},
  {no:"08",title:"Procurement & Contracts",courses:["Advanced Buyers Essential Skills · 2 days","Strategic Procurement Masterclass (SPM) · 3 days","Contracts Management Essentials · 2 days","Sustainable Procurement · 2 days","Procurement Negotiation Masterclass · 2 days","Certificate in AI for Procurement · 1 day","Warehouse & Operations Management · 2 days","Logistics Management Specialist (LMS) · 2 days","Supply Chain Leadership Strategies · 3 days","AI for Supply Chain Executives · 1 day"]},
  {no:"09",title:"Aviation, Hospitality & Tourism",courses:["Train the Trainer for Cabin Crew · 3 days","Train the Trainer for Technical Team · 3 days","Aviation Leadership Excellence · 2 days","Decision-Making Under Operational Pressure · 1 day","Aviation Operations Excellence · 3 days","Airport Operations Management · 3 days","Ground Handling Best Practices · 2 days","Human Factors in Aviation · 2 days","Aviation Compliance & Regulatory Awareness · 1 day","Airline Sales & Revenue Growth · 2 days","Five-Star Customer Service Excellence · 2 days","Telephone & Reservation Etiquette · 1 day","Hospitality Sales Excellence · 1 day","Professional Etiquette & Business Protocol · 1 day"]},
  {no:"10",title:"Quality Management & Process Improvement",courses:["Certified Six Sigma Green Belt (CSSGB) · 2 days","Certified Six Sigma Black Belt (CSSBB) · 3 days","Principles of Quality Management · 2 days","Operational Excellence through Quality Management · 1 day","Business Process Mapping & Optimization · 1 day","Kaizen for Continuous Improvement · 1 day"]},
  {no:"11",title:"Team Building",courses:["Innovation & Collaboration","Leadership & Building High-Trust Teams","Communication & Team Effectiveness","Problem Solving & Critical Thinking","Employee Engagement & Motivation","Trust, Resilience & Change","Customer Service & Service Excellence"]}
];

const solutions=[
  {no:"01",title:"Diagnose",text:"Clarify business priorities, capability gaps, learner needs and meaningful measures of success."},
  {no:"02",title:"Design",text:"Shape content, case studies, activities and delivery around your organisation and industry context."},
  {no:"03",title:"Deliver",text:"Engage learners through in-person or live online instructor-led programmes in English or Arabic."},
  {no:"04",title:"Evaluate",text:"Review participation, application and progress against the outcomes agreed at the outset."}
];

const categoryImages:Record<string,string>={
  "01":"/images/course-leadership.png",
  "02":"/images/course-professional-excellence.png",
  "03":"/images/corporate-ai-data.png",
  "04":"/images/home-learning-hero.png",
  "05":"/images/course-cma.png",
  "06":"/images/corporate-it-skills.png",
  "07":"/images/course-entrepreneurship.png",
  "08":"/images/course-cpip.png",
  "09":"/images/corporate-aviation.png",
  "10":"/images/course-cism.png",
  "11":"/images/corporate-training-hero.png"
};

const catalogCategories=categories.map(category=>({...category,courses:courseData.filter(course=>course.categoryNo===category.no)}));

export default function CorporateTraining(){return <main><SiteHeader/><section className="corporate-hero"><div className="corporate-hero-photo"/><div className="corporate-hero-copy"><div className="section-kicker light">Corporate Training</div><h1>Capability designed<br/>around your <em>business.</em></h1><p>More than 100 focused programmes across leadership, AI, HR, finance, technology, supply chain, aviation and service excellence.</p><a className="btn-gold" href="#corporate-lead-capture">Discuss your training needs <span>↗</span></a></div></section><CorporateLeadForm categories={categories.map(category=>category.title)}/><section className="corporate-catalog-intro section-pad"><div><div className="section-kicker">Corporate programme catalogue</div><h2>Skills that move<br/>organisations forward.</h2></div><div><p className="lead">Choose a focused course or let ETI build a customised learning journey around your business goals.</p><p>Open any course to explore its brochure-inspired overview, objectives, learner profile and detailed curriculum.</p></div></section><section className="corporate-category-grid section-pad">{catalogCategories.map(category=><article id={`category-${category.no}`} className={category.no==="11"?"corporate-category team-building-category":"corporate-category"} key={category.no}><div className={`corporate-category-image corporate-category-image-${category.no}`}><img src={categoryImages[category.no]} alt={`${category.title} corporate training`} loading="lazy"/><span>ETI Corporate Learning</span></div><header><span>{category.no}</span><div><small>Corporate training category</small><h2>{category.title}</h2></div><strong>{String(category.courses.length).padStart(2,"0")} programmes</strong></header><ol>{category.courses.map((course,index)=><li key={course.slug}><span>{String(index+1).padStart(2,"0")}</span><Link href={`/corporate-training/courses/${course.categorySlug}/${course.slug}`}><p>{course.title}</p><small>{course.duration}</small><i>↗</i></Link></li>)}</ol></article>)}</section><section className="corporate-partnership section-pad"><div className="corporate-intro"><div className="section-kicker light">A focused partnership</div><h2>From business need<br/>to measurable impact.</h2><p>Fully customised for small teams, large corporate groups, classroom, virtual, indoor, outdoor or offsite delivery.</p></div><div className="corporate-solution-list">{solutions.map(x=><article key={x.no}><span>{x.no}</span><div><h3>{x.title}</h3><p>{x.text}</p></div></article>)}</div></section><section className="corporate-contact"><div><span>Build capability that lasts.</span><h2>Let&apos;s design your programme.</h2></div><div><p>Speak with our corporate learning team about your organisation, audience and objectives.</p><a className="btn-gold" href="#corporate-lead-capture">Start your corporate enquiry <span>↗</span></a></div></section><SiteFooter/></main>}
