import Link from "next/link";
import {SiteFooter,SiteHeader} from "../components";
import programData from "./program-data.json";

const established=[
  {slug:"certified-management-accountant",title:"Certified Management Accountant (CMA)",image:"/images/course-cma.png",tag:"96 hours · Classroom / Virtual",text:"Develop strategic finance expertise in planning, performance, analytics and business decision-making."},
  {slug:"certified-procurement-international-manager",title:"Certified Procurement International Manager (CPIM)",image:"/images/course-cpim.png",tag:"12 training hours · Flexible",text:"Build advanced procurement leadership, strategic sourcing and supplier-management capability."},
  {slug:"certified-procurement-international-professional",title:"Certified Procurement International Professional (CPIP)",image:"/images/course-cpip.png",tag:"12 training hours · Flexible",text:"Master procurement planning, sourcing, supplier evaluation, contracts and negotiation."}
];
const pro={slug:"pro-training",title:"PRO Training",image:"/images/course-leadership.png",tag:"12 hours · Classroom / Online",text:"Gain practical command of UAE visa, labour, licensing and government liaison procedures."};
const brochurePrograms=programData.map(program=>({slug:program.slug,title:program.title,image:program.cover,tag:`${program.duration} · Flexible`,text:program.summary.split(/(?<=[.!?])\s/)[0]}));
const courses=[...established,...brochurePrograms,pro];

export default function Programs(){return <main><SiteHeader/><section className="programs-hero"><div className="programs-hero-photo"/><div className="programs-hero-copy"><div className="section-kicker light">Professional programmes</div><h1>Programs built for<br/><em>meaningful progress.</em></h1><p>Thirty-eight focused qualifications spanning artificial intelligence, finance, procurement, supply chain, compliance, aviation, engineering, HR, communication, hospitality and professional skills.</p></div></section><section className="catalog section-pad"><div className="catalog-intro"><span>38 professional programs</span><p>Choose the qualification that meets your next professional challenge.</p></div><div className="course-grid certification-grid expanded-program-grid">{courses.map((course,index)=><Link href={`/programs/${course.slug}`} className="course-card" key={course.slug}><div className="course-card-image"><img src={course.image} alt={`${course.title} programme`} loading="lazy"/><div className="course-card-top"><span>{String(index+1).padStart(2,"0")}</span><i>↗</i></div></div><div><small>{course.tag}</small><h2>{course.title}</h2><p>{course.text}</p></div><strong>View programme <span>→</span></strong></Link>)}</div></section><section className="corporate-band"><div><span>For organisations</span><h2>Leadership and business capability.</h2></div><p>Explore more than 100 customisable courses designed for organisational learning and measurable workplace impact.</p><Link href="/corporate-training">Explore corporate training ↗</Link></section><SiteFooter/></main>}
