import type {Metadata} from "next";
import {SiteFooter,SiteHeader} from "../../components";

export const metadata:Metadata={title:"Expert Trainers | Entrepôt Training Institute",description:"Meet Entrepôt Training Institute's industry practitioners in aviation, logistics, procurement, leadership, customer service and professional development."};

const trainers=[
  {no:"01",name:"Sajeev Gulati",role:"Founder · Trainer · Mentor · Leader",image:"/images/trainer-sajeev-gulati.jpg",position:"center 42%",experience:"21+ years of experience · 5,000+ learners trained",bio:"An industry practitioner and educator whose extensive aviation, airport and logistics experience turns complex operational subjects into practical learning.",expertise:["Logistics & supply chain","Airport operations & management","Air cargo handling","Procurement & inventory management"],credentials:["MBA, International Marketing & Management","IATA DGR Category 6","IATA Airport Management","Customs Broker Licence · CBLR 2018"]},
  {no:"02",name:"Sheetal Murthy",role:"Trainer · Mentor · Leader",image:"/images/trainer-sheetal-murthy.jpg",position:"center 25%",experience:"20+ years of experience · 10,000+ training hours",bio:"A multidisciplinary learning leader with a consistent record of high learner achievement across aviation, travel, procurement and supply-chain programmes.",expertise:["Aviation, travel & tourism","Supply chain & logistics","Career and interview readiness","Interpersonal & professional skills"],credentials:["IFPSM CISM & CPIP","IATA Passenger Ground Services","NLP Coaching","Six Sigma Green Belt"]},
  {no:"03",name:"Reena Dsouza",role:"Trainer · Operations Head",image:"/images/trainer-reena-dsouza.jpg",position:"center 20%",experience:"6+ years of industry experience and 3+ years in cabin crew training",bio:"An aviation and customer-experience professional who brings frontline insight, emotional intelligence and an engaging learning style to every classroom.",expertise:["Cabin crew & aviation safety","Customer service excellence","Communication & conflict resolution","Grooming, poise & cultural sensitivity"],credentials:["Bachelor of Commerce","Diploma in Business Administration","First Aid & Aviation Security","Dangerous Goods Handling"]},
  {no:"04",name:"Aarti Khanna",role:"Corporate Trainer · L&D Professional · Financial Services Expert",image:"/images/trainer-aarti-khanna.jpg",position:"center 24%",experience:"25+ years of banking and financial-services experience",bio:"An MBA and BFSI practitioner who delivers structured, highly interactive learning that connects technical competence and behavioural effectiveness with measurable business outcomes.",expertise:["AML & regulatory compliance","Retail lending, credit & risk","Wealth management products","Sales, customer service & executive presence"],credentials:["Master of Business Administration","Co-Founder & Director · Graded Financial Services","BFSI & retail lending specialist","Corporate trainer & management consultant"]},
  {no:"05",name:"Thakur Ajit Singh",role:"Corporate Trainer · Business Consultant",image:"/images/trainer-thakur-ajit-singh.png",position:"center 22%",experience:"30+ years of experience · 5,000+ professionals trained",bio:"A business leader and facilitator known for practical, experience-led programmes that connect professional capability with measurable workplace outcomes.",expertise:["Leadership & business communication","Sales excellence & tele-sales","Public speaking & presentations","Financial planning & productivity"],credentials:["Bachelor of Engineering · Electronics","Master of Business Administration","PG Diploma · Investment & Tax Planning","Business transformation specialist"]}
];

export default function Trainers(){return <main><SiteHeader/><section className="people-hero trainers-hero" style={{backgroundImage:"linear-gradient(90deg,rgba(14,27,10,.98),rgba(14,27,10,.78) 56%,rgba(14,27,10,.2)),url('/images/course-professional-excellence.png')"}}><div><div className="section-kicker light">About Us / Trainers</div><h1>Industry expertise.<br/><em>Human impact.</em></h1><p>Meet the practitioners, mentors and leaders who bring real-world perspective into every Entrepôt learning experience.</p></div></section><section className="trainer-intro section-pad"><div><div className="section-kicker">Our faculty</div><h2>Learn from people<br/>who have done it.</h2></div><div><p className="lead">Credibility in the classroom begins with experience beyond it.</p><p>Our faculty combines deep industry knowledge with the craft of facilitation. Each trainer turns proven frameworks into practical insight, helping learners build confidence, capability and lasting professional value.</p></div></section><section className="trainer-directory section-pad" aria-label="Entrepôt trainer profiles">{trainers.map((trainer,index)=><article className={`trainer-profile ${index%2?"trainer-profile-reverse":""}`} key={trainer.name}><div className="trainer-photo"><img src={trainer.image} alt={`${trainer.name}, ${trainer.role}`} style={{objectPosition:trainer.position}}/><span>{trainer.no} / Faculty</span></div><div className="trainer-copy"><span className="trainer-number">Profile {trainer.no}</span><h2>{trainer.name}</h2><p className="trainer-role">{trainer.role}</p><p className="trainer-experience">{trainer.experience}</p><p className="trainer-bio">{trainer.bio}</p><div className="trainer-details"><div><h3>Core expertise</h3><ul>{trainer.expertise.map(item=><li key={item}>{item}</li>)}</ul></div><div><h3>Credentials</h3><ul>{trainer.credentials.map(item=><li key={item}>{item}</li>)}</ul></div></div></div></article>)}</section><section className="trainer-closing section-pad"><div className="section-kicker light">The ETI standard</div><h2>Practical knowledge.<br/><em>Purposeful delivery.</em></h2><p>Every learning experience is designed to move beyond theory—into confident application, stronger performance and measurable professional growth.</p></section><SiteFooter/></main>}
