"use client";

import {FormEvent,useMemo,useRef,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {optimizedImage} from "../image";
import TestimonialVideoGallery from "../TestimonialVideoGallery";

type ComplianceCourse={title:string;url:string;group:string};

const complianceCourses:ComplianceCourse[]=[
  {title:"AML Compliance CPD for Exchange Houses",url:"/programs/aml-compliance-cpd-exchange-houses",group:"Banking & Financial Services"},
  {title:"Compliance for Virtual Asset Businesses",url:"/programs/compliance-virtual-asset-businesses",group:"FinTech & Payments"},
  {title:"Compliance for UAE Trading Companies",url:"/programs/compliance-uae-trading-companies",group:"Commercial & Regulated Businesses"},
  {title:"Compliance for Trust & Company Service Providers",url:"/programs/compliance-trust-company-service-providers",group:"Professional & Corporate Services"},
  {title:"Compliance for Payment Services & FinTech",url:"/programs/compliance-payment-services-fintech",group:"FinTech & Payments"},
  {title:"Compliance for Legal Consultants & Law Firms",url:"/programs/compliance-legal-consultants-law-firms",group:"Professional & Corporate Services"},
  {title:"Compliance for the Insurance Sector",url:"/programs/compliance-insurance-sector",group:"Commercial & Regulated Businesses"},
  {title:"Compliance for Independent Accountants & Auditors",url:"/programs/compliance-independent-accountants-auditors",group:"Professional & Corporate Services"},
  {title:"Compliance for Dealers in Precious Metals & Stones",url:"/programs/compliance-dpms",group:"Sector-Specific Compliance"},
  {title:"Compliance for the UAE Real Estate Sector",url:"/programs/compliance-uae-real-estate-sector",group:"Sector-Specific Compliance"},
  {title:"Compliance for Banks & Financial Institutions",url:"/programs/compliance-banks-financial-institutions",group:"Banking & Financial Services"},
];

const courseGroups=["All programmes","Banking & Financial Services","FinTech & Payments","Professional & Corporate Services","Commercial & Regulated Businesses","Sector-Specific Compliance"];
const groupDescriptions:Record<string,string>={
  "Banking & Financial Services":"Practical AML, regulatory and financial-crime compliance learning for banks, financial institutions and exchange houses.",
  "FinTech & Payments":"Compliance learning for payment services, FinTech businesses and organisations operating in the virtual-asset ecosystem.",
  "Professional & Corporate Services":"Role-relevant compliance programmes for TCSPs, legal practices, accountants and auditors.",
  "Commercial & Regulated Businesses":"Sector-aware compliance learning for UAE trading companies and insurance-sector professionals.",
  "Sector-Specific Compliance":"Focused AML and compliance capability for real estate businesses and dealers in precious metals and stones.",
};
const CORPORATE_CONTACT={whatsapp:"",phone:"",email:""};
const clientPlaceholders=Array.from({length:8},(_,index)=>`Client Logo ${String(index+1).padStart(2,"0")}`);
const benefits=[
  ["01","Built around your compliance priorities","Training aligned with your organisation’s AML, regulatory, risk and compliance priorities."],
  ["02","Relevant to your sector","Learning contextualised for banking, exchange houses, FinTech, payments, virtual assets, real estate, insurance, trading and professional services."],
  ["03","Practical for your teams","Realistic workplace scenarios and role-relevant examples make compliance learning practical."],
  ["04","Designed for measurable learning","Clear learning objectives and outcomes help stakeholders understand the value of the training."],
  ["05","Practitioner-led expertise","Experienced professionals connect compliance frameworks with real workplace requirements."],
];
const industries=[
  ["Banking & Financial Institutions","AML controls, customer due diligence, transaction monitoring, risk-based compliance and financial crime prevention."],
  ["Exchange Houses","AML responsibilities, regulatory awareness and practical compliance considerations for exchange-house teams."],
  ["FinTech & Payment Services","Compliance considerations for digital financial services, payment businesses and emerging financial models."],
  ["Virtual Asset Businesses","Compliance awareness and risk considerations for businesses operating within the virtual-asset ecosystem."],
  ["UAE Real Estate","AML and compliance considerations relevant to UAE real estate businesses and their teams."],
  ["Precious Metals & Stones","Compliance practices relevant to dealers in precious metals and stones."],
  ["Insurance","Compliance awareness tailored to insurance-sector professionals."],
  ["UAE Trading Companies","Practical compliance learning relevant to trading businesses."],
  ["Legal & Professional Services","Compliance learning relevant to legal consultants, law firms, accountants and auditors."],
  ["Trust & Company Service Providers","Sector-specific compliance responsibilities and practical AML awareness."],
];
const trainers=[
  {name:"Sajeev Gulati",role:"Founder · Trainer · Mentor · Leader",image:"/images/trainer-sajeev-gulati.jpg",experience:"21+ years of experience · 5,000+ learners trained",focus:"Logistics, supply chain, airport operations and procurement"},
  {name:"Sheetal Murthy",role:"Trainer · Mentor · Leader",image:"/images/trainer-sheetal-murthy.jpg",experience:"20+ years of experience · 10,000+ training hours",focus:"Aviation, travel, supply chain and professional skills"},
  {name:"Reena Dsouza",role:"Trainer · Operations Head",image:"/images/trainer-reena-dsouza.jpg",experience:"6+ years of industry experience and 3+ years in cabin crew training",focus:"Cabin crew, aviation safety, customer service, communication and conflict resolution"},
  {name:"Aarti Khanna",role:"Corporate Trainer · L&D Professional",image:"/images/trainer-aarti-khanna.jpg",experience:"25+ years in banking and financial services",focus:"AML, compliance, credit, risk, sales and executive presence"},
  {name:"Thakur Ajit Singh",role:"Corporate Trainer · Business Consultant",image:"/images/trainer-thakur-ajit-singh.png",experience:"30+ years of experience · 5,000+ professionals trained",focus:"Leadership, communication, sales and productivity"},
];
const socialLinks=[
  ["Facebook","https://www.facebook.com/entrepottraininginstitute"],
  ["Instagram","https://www.instagram.com/entrepottraininginstitute/"],
  ["LinkedIn","https://www.linkedin.com/company/entrepot-training-institute/"],
  ["YouTube","https://www.youtube.com/@EntrepotTrainingInstitute"],
];
const methods=[
  ["01","Diagnose","Align on the business priority, audience, capability gap and the evidence stakeholders need."],
  ["02","Design","Build the right mix of content, cases, activities and delivery around your organisation."],
  ["03","Deliver","Create an engaging learning experience focused on participation, practice and workplace relevance."],
  ["04","Evaluate","Review learning and application against the outcomes agreed at the start."],
];
const outcomes=["AML & Regulatory Awareness","Risk-Based Decision Making","Stronger Compliance Controls","Financial Crime Awareness","Role-Specific Capability","Regulatory Readiness","Consistent Compliance Culture","Practical Workplace Application"];
const facilitationGallery=[
  {image:"/images/training-air-facilitation-cohort-outdoor.jpeg",alt:"Overseas Facilitation in Air Transportation Handling cohort with ETI facilitators",caption:"Overseas cohort"},
  {image:"/images/training-air-facilitation-session-01.jpeg",alt:"Facilitator teaching the key pillars of air transportation facilitation",caption:"Learning in action"},
  {image:"/images/training-air-facilitation-session-02.jpeg",alt:"Interactive Facilitation in Air Transportation Handling session",caption:"Practical facilitation"},
  {image:"/images/training-air-facilitation-cohort-indoor.jpeg",alt:"Air transportation learners and programme facilitators",caption:"Collaborative learning"},
  {image:"/images/training-air-facilitation-group.jpeg",alt:"Programme participants celebrating their overseas learning experience",caption:"Team experience"},
  {image:"/images/training-air-facilitation-certificate.jpeg",alt:"Facilitation in Air Transportation Handling graduate receiving his certificate",caption:"Certificate presentation"},
  {image:"/images/training-air-facilitation-completion.jpeg",alt:"Air transportation graduates celebrating successful programme completion",caption:"Programme completion"},
];
const overseasCorporateGallery=[
  {image:"/images/training-air-complaints-graduates.jpeg",alt:"Overseas corporate training graduates with ETI facilitators and corporate representatives",caption:"Celebrating achievement"},
  {image:"/images/training-air-complaints-cohort.jpeg",alt:"Overseas corporate training cohort with programme facilitators",caption:"The corporate cohort"},
  {image:"/images/training-air-complaints-facilitation-01.jpeg",alt:"ETI facilitator presenting during the overseas corporate training programme",caption:"Expert facilitation"},
  {image:"/images/training-air-complaints-facilitation-02.jpeg",alt:"Facilitator leading an overseas corporate learning session",caption:"Learning in action"},
  {image:"/images/training-air-complaints-celebration.jpeg",alt:"Graduate and programme team celebrating successful corporate training completion",caption:"Programme milestone"},
  {image:"/images/training-air-complaints-certificate.jpeg",alt:"Overseas corporate training graduate receiving her completion certificate",caption:"Certificate presentation"},
];
const financialConsultantsAuditorsGallery=[
  {image:"/images/training-financial-consultants-auditors-01.jpeg",alt:"Financial consultants and auditors celebrating completion of their corporate training programme with certificates",caption:"Celebrating professional achievement"},
  {image:"/images/training-financial-consultants-auditors-02.jpeg",alt:"Corporate training cohort of financial consultants and auditors holding their certificates of achievement",caption:"Corporate cohort completion"},
];
const faqs=[
  ["Can AML and compliance programmes be customised for our organisation?","Yes. Programmes can be adapted around the organisation’s business context, audience, capability requirements and relevant compliance priorities."],
  ["Can the training be tailored to our industry?","Yes. Training can be contextualised for sectors including banking, exchange houses, FinTech, payments, virtual assets, real estate, insurance, trading, DPMS and professional services."],
  ["Can the training be designed for specific teams or roles?","Yes. Programmes can be structured for compliance, risk, finance, legal, internal audit, operations, HR/L&D and other relevant teams."],
  ["Can multiple departments participate in the same programme?","Yes. Corporate programmes can be structured for cross-functional audiences where appropriate, with examples relevant to different responsibilities."],
  ["Can training be delivered at our premises?","Yes. Corporate programmes can be delivered in-house, subject to planning and programme requirements."],
  ["Can AML training be delivered online?","Yes. Live online and blended delivery options are available alongside classroom and in-house formats."],
  ["Can the programme focus on our specific compliance priorities?","Yes. The learning brief can be aligned with the organisation’s sector, business requirements, employee responsibilities and compliance objectives."],
  ["Which AML and compliance programmes are available?","This page features 11 programmes covering banking, exchange houses, FinTech, virtual assets, trading companies, trust and company service providers, legal services, insurance, accountants and auditors, precious metals and stones, and real estate."],
  ["How do we request a corporate compliance training recommendation?","Complete the enquiry form and select the relevant course or programme. The ETI corporate learning team can then understand the requirement and recommend an appropriate training approach."],
];

function WhatsAppIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 11.7a8.5 8.5 0 0 1-12.6 7.4L3.5 20.5l1.4-4.2A8.5 8.5 0 1 1 20.5 11.7Z"/><path d="M8.1 7.6c.2-.5.5-.5.8-.5h.4c.2 0 .4.1.5.4l.8 1.9c.1.3 0 .5-.1.7l-.6.8c-.2.2-.2.4 0 .7.6 1.1 1.5 2 2.6 2.6.3.2.5.1.7-.1l.9-1.1c.2-.2.4-.3.7-.2l1.9.9c.3.1.4.3.4.5 0 .4-.2 1.5-.8 2-.6.5-1.3.8-2.2.6-1-.2-2.7-.8-4.5-2.4-1.5-1.4-2.6-3.1-2.9-4.2-.3-1-.1-1.9.3-2.4.3-.3.7-.6 1.1-.2Z"/></svg>}
function MailIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="1"/><path d="m4 7 8 6 8-6"/></svg>}
function SocialIcon({name}:{name:string}){if(name==="Instagram")return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3.5" y="3.5" width="17" height="17" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.4" cy="6.8" r=".8"/></svg>;if(name==="LinkedIn")return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3.5" y="3.5" width="17" height="17" rx="2"/><path d="M8 10v7M8 7.2v.2M11.5 17v-7m0 3c.7-2.2 4.5-2.4 4.5.9V17"/></svg>;if(name==="YouTube")return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="6" width="18" height="12" rx="4"/><path d="m10 9 5 3-5 3Z"/></svg>;return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 21v-8h3l.5-3H14V8.2c0-1 .4-1.7 1.8-1.7H18V3.8c-.7-.1-1.7-.3-3-.3-3 0-4.8 1.8-4.8 5.1V10H7v3h3.2v8"/></svg>}

function LeadForm({compact=false}:{compact?:boolean}){
  const router=useRouter();
  const[status,setStatus]=useState<"idle"|"sending"|"sent"|"error">("idle");
  const busy=useRef(false);
  async function submit(event:FormEvent<HTMLFormElement>){
    event.preventDefault();if(busy.current)return;busy.current=true;setStatus("sending");
    const form=event.currentTarget;const data=new FormData(form);data.append("Lead source","Customised Corporate AML & Compliance Training Programmes page");data.append("_subject",`Corporate AML and compliance training lead — ${data.get("Course")||"General"}`);data.append("_template","table");data.append("_captcha","false");
    try{const response=await fetch("https://formsubmit.co/ajax/courses@entrepot.ae",{method:"POST",headers:{Accept:"application/json"},body:data});if(!response.ok)throw new Error();const gtag=(window as typeof window&{gtag?:(a:string,b:string,c:Record<string,string|number>)=>void}).gtag;if(gtag)gtag("event","conversion",{send_to:"AW-18398125830/CaK1CIvS9-YcEIa-9MRE",value:1,currency:"AED"});form.reset();setStatus("sent");router.push("/thank-you")}catch{busy.current=false;setStatus("error")}
  }
  if(status==="sent")return <div className="pct-form-success" role="status"><span>Thank you</span><h3>Your compliance training brief is with us.</h3><p>Our corporate learning team will review your requirements and contact you to discuss the right next step.</p></div>;
  return <form className={`pct-lead-form ${compact?"pct-lead-form-compact":""}`} onSubmit={submit}>
    <div className="pct-form-heading"><span>Plan your compliance training</span><h2>{compact?"Get a tailored recommendation.":"Brief us on your compliance priorities."}</h2><p>Share your requirement and an ETI corporate learning specialist will help identify the relevant programme, delivery format and next step.</p></div>
    <div className="pct-field-row"><label>Full name *<input name="Name" autoComplete="name" required placeholder="Your full name"/></label><label>Organisation *<input name="Organisation" autoComplete="organization" required placeholder="Company name"/></label></div>
    <div className="pct-field-row"><label>Business email *<input name="Email" type="email" autoComplete="email" required placeholder="you@company.com"/></label><label>Phone number *<input name="Phone" type="tel" autoComplete="tel" required placeholder="+971"/></label></div>
    <label>Courses We Offer *<select name="Course" required defaultValue=""><option value="" disabled>Select a course</option>{complianceCourses.map(course=><option key={course.url}>{course.title}</option>)}</select></label>
    {!compact&&<label>What should this training help your people achieve?<textarea name="Requirements" rows={3} placeholder="Audience, compliance priority, business objective, preferred dates or delivery format"/></label>}
    <label className="pct-consent"><input name="Consent" type="checkbox" required value="Yes"/><span>I agree to be contacted about this corporate training enquiry.</span></label>
    {status==="error"&&<p className="pct-error" role="alert">We couldn&apos;t submit this enquiry. Please try again or contact us directly.</p>}
    <button type="submit" disabled={status==="sending"}>{status==="sending"?"Sending…":"Request a tailored recommendation"}<span>↗</span></button>
    <small>No generic mailing lists. Your details are used only to respond to this training enquiry.</small>
  </form>
}

export default function ComplianceCorporateLanding(){
  const[filter,setFilter]=useState(courseGroups[0]);
  const[query,setQuery]=useState("");
  const filtered=useMemo(()=>complianceCourses.filter(course=>(filter===courseGroups[0]||course.group===filter)&&course.title.toLowerCase().includes(query.toLowerCase())),[filter,query]);
  const grouped=useMemo(()=>courseGroups.slice(1).map(group=>({group,courses:filtered.filter(course=>course.group===group)})).filter(item=>item.courses.length),[filtered]);
  return <main className="pct-page pct-compliance-page">
    <header className="pct-header"><Link href="/" aria-label="Entrepôt Training Institute home"><img src="/entrepot-logo-transparent.png" alt="Entrepôt Training Institute"/></Link><div className="pct-header-actions"><div className="pct-header-contact"><a href="https://wa.me/971544177480?text=Hi%2C%20I%20want%20to%20discuss%20customised%20corporate%20training" target="_blank" rel="noopener noreferrer" aria-label="WhatsApp +971 544 177480"><WhatsAppIcon/><span>+971 544 177480</span></a><a href="https://wa.me/971545353558?text=Hi%2C%20I%20want%20to%20discuss%20customised%20corporate%20training" target="_blank" rel="noopener noreferrer" aria-label="WhatsApp +971 545 353 558"><WhatsAppIcon/><span>+971 545 353 558</span></a></div><nav className="pct-header-socials" aria-label="Entrepôt social media">{socialLinks.map(([name,url])=><a href={url} target="_blank" rel="noopener noreferrer" aria-label={`Visit ETI on ${name}`} title={name} key={name}><SocialIcon name={name}/></a>)}</nav><a className="pct-header-cta" href="mailto:programs@entrepot.ae" aria-label="Email programs at Entrepôt Training Institute"><MailIcon/><span>programs@entrepot.ae</span></a></div></header>
    <section className="pct-hero"><div className="pct-hero-image"/><div className="pct-hero-copy"><span>For L&amp;D, compliance and business leaders</span><h1>Turn compliance priorities into practical AML training your people can <em>apply.</em></h1><p>Shape sector-relevant AML and compliance learning around regulatory requirements, industry risks, business context, employee roles and your organisation&apos;s learning objectives.</p><div className="pct-hero-actions"><a href="#enquire">Get a tailored compliance training recommendation <b>↗</b></a><a href="#catalogue">Review 11 compliance programmes</a></div><div className="pct-hero-proof"><span>Aligned to regulatory priorities</span><span>Sector-specific learning</span><span>In-house · Online · Blended</span></div></div><aside id="enquire"><LeadForm compact/></aside></section>
    <section className="pct-trust"><div className="pct-trust-stats"><article><strong>100+</strong><span>Programme options</span></article><article><strong>11</strong><span>Capability areas</span></article><article><strong>2</strong><span>Regional offices</span></article><article><strong>4</strong><span>Flexible formats</span></article></div><div className="pct-client-wall"><div><span>Selected organisations</span><h2>Learning delivered. <em>Confidence earned.</em></h2><p>Client logos for this AML and compliance training page will be added when approved assets are provided.</p></div><div>{clientPlaceholders.map((name,index)=><figure key={name}><span>{String(index+1).padStart(2,"0")}</span><div className="pct-client-placeholder" aria-label={`${name} placeholder`}>{name}</div><figcaption>{name}</figcaption></figure>)}</div></div><div className="pct-logo-wall"><span>Affiliations &amp; accreditations</span><div><img src={optimizedImage("/images/accreditation-iso-9001-transparent.png",420,82)} alt="ISO 9001:2015"/><img src={optimizedImage("/images/affiliation-dubai-knowledge-transparent.png",520,82)} alt="Dubai Knowledge"/><img src={optimizedImage("/images/accreditation-cpd-transparent.png",420,82)} alt="CPD Standards Office"/><img src={optimizedImage("/images/affiliation-cilt-transparent.png",620,82)} alt="Chartered Institute of Logistics and Transport"/><img src={optimizedImage("/images/affiliation-ifpsm-transparent.png",640,82)} alt="International Federation of Purchasing and Supply Management"/></div></div></section>
    <section className="pct-section pct-why"><div className="pct-section-head"><span>A stronger L&amp;D partner</span><h2>Move from a compliance request to a structured, practical <em>learning programme.</em></h2><p>Bring us the compliance priority. ETI helps shape a sector-relevant learning response, connect it to workplace responsibilities and define meaningful outcomes.</p></div><div className="pct-benefit-grid">{benefits.map(([no,title,text])=><article key={no}><span>{no}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section id="catalogue" className="pct-section pct-catalogue"><div className="pct-section-head"><span>Build your shortlist</span><h2>Build your AML &amp; compliance training shortlist.</h2><p>Help L&amp;D, compliance and business leaders identify the programmes most relevant to their organisation, sector and compliance priorities.</p></div><div className="pct-catalogue-tools"><input aria-label="Search AML and compliance programmes" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search by course or sector…"/><div>{courseGroups.map(group=><button type="button" className={filter===group?"active":""} onClick={()=>setFilter(group)} key={group}>{group}</button>)}</div></div><div className="pct-course-groups">{grouped.map(item=><details key={item.group} open><summary><div><span>{String(courseGroups.indexOf(item.group)).padStart(2,"0")}</span><strong>{item.group}</strong></div><small>{item.courses.length} programmes</small></summary><p>{groupDescriptions[item.group]}</p><div>{item.courses.map(course=><Link href={course.url} key={course.url}><span>{course.title}</span><small>View programme</small><b>↗</b></Link>)}</div></details>)}</div>{!grouped.length&&<p className="pct-no-results">No exact match? Share your compliance priority and ETI will help identify the most relevant programme.</p>}</section>
    <section className="pct-section pct-industries"><div className="pct-section-head"><span>Industry-aware learning</span><h2>Industry-aware compliance learning.</h2><p>AML and compliance requirements differ across industries. Training should reflect the regulatory environment, operational realities and responsibilities of the teams being trained.</p></div><div>{industries.map(([title,text],index)=><article key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="pct-training-gallery" aria-labelledby="compliance-facilitation-gallery-title"><div className="pct-training-gallery-head"><div><span>Training gallery / Overseas corporate delivery</span><h2 id="compliance-facilitation-gallery-title">Facilitation in Air<br/><em>Transportation Handling.</em></h2></div><div><strong>Successfully completed</strong><p>We are proud to have successfully completed an overseas batch of Facilitation in Air Transportation Handling for one of our esteemed corporate clients.</p></div></div><div className="pct-training-gallery-grid">{facilitationGallery.map((photo,index)=><figure className={`pct-training-gallery-photo pct-training-gallery-photo-${index+1}`} key={photo.image}><img src={optimizedImage(photo.image,index===0||index===4?1200:760,82)} alt={photo.alt} loading="lazy" decoding="async"/><figcaption><span>{String(index+1).padStart(2,"0")}</span>{photo.caption}</figcaption></figure>)}</div></section>
    <section className="pct-training-gallery pct-training-gallery-light" aria-labelledby="compliance-overseas-gallery-title"><div className="pct-training-gallery-head"><div><span>Training gallery / International delivery</span><h2 id="compliance-overseas-gallery-title">Overseas Corporate<br/><em>Training.</em></h2></div><div><strong>Successfully completed</strong><p>We are proud to have successfully completed an overseas corporate training batch for one of our esteemed corporate clients.</p></div></div><div className="pct-training-gallery-grid pct-overseas-corporate-grid">{overseasCorporateGallery.map((photo,index)=><figure className={`pct-training-gallery-photo pct-training-gallery-photo-${index+1}`} key={photo.image}><img src={optimizedImage(photo.image,index===0||index===1?1200:760,82)} alt={photo.alt} loading="lazy" decoding="async"/><figcaption><span>{String(index+1).padStart(2,"0")}</span>{photo.caption}</figcaption></figure>)}</div></section>
    <section className="pct-training-gallery" aria-labelledby="compliance-financial-gallery-title"><div className="pct-training-gallery-head"><div><span>Training gallery / Corporate learning</span><h2 id="compliance-financial-gallery-title">Financial Consultants<br/><em>&amp; Auditors.</em></h2></div><div><strong>Successfully completed</strong><p>We are proud to have successfully completed a corporate training batch for financial consultants and auditors from one of our esteemed corporate clients.</p></div></div><div className="pct-training-gallery-grid pct-financial-gallery-grid">{financialConsultantsAuditorsGallery.map((photo,index)=><figure className={`pct-training-gallery-photo pct-training-gallery-photo-${index+1}`} key={photo.image}><img src={optimizedImage(photo.image,1200,84)} alt={photo.alt} loading="lazy" decoding="async"/><figcaption><span>{String(index+1).padStart(2,"0")}</span>{photo.caption}</figcaption></figure>)}</div></section>
    <TestimonialVideoGallery context="corporate"/>
    <section className="pct-section pct-experts"><div className="pct-section-head"><span>Practitioner-led learning</span><h2>Give your people expertise they can use.</h2><p>ETI facilitators connect robust frameworks with the realities of the workplace, creating credible learning for experienced professionals.</p></div><div className="pct-expert-grid">{trainers.map(trainer=><article key={trainer.name}><img src={optimizedImage(trainer.image,760,80)} alt={`${trainer.name}, ${trainer.role}`} loading="lazy"/><div><span>{trainer.role}</span><h3>{trainer.name}</h3><strong>{trainer.experience}</strong><p>{trainer.focus}</p></div></article>)}</div></section>
    <section className="pct-method"><div className="pct-section-head"><span>A clear engagement process</span><h2>Make the learning plan easier to take to stakeholders.</h2><p>From the first brief to evaluation, each stage keeps the programme connected to the need it was designed to address.</p></div><div>{methods.map(([no,title,text])=><article key={no}><span>{no}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="pct-section pct-outcomes"><div className="pct-section-head"><span>Business-relevant compliance outcomes</span><h2>Connect compliance learning priorities to performance.</h2><p>Focus the engagement on practical AML and compliance capabilities that matter to your people, leaders and organisation.</p></div><div>{outcomes.map((outcome,index)=><article key={outcome}><span>{String(index+1).padStart(2,"0")}</span><p>{outcome}</p></article>)}</div></section>
    <section className="pct-delivery"><div><span>Flexible delivery</span><h2>Make rollout work across teams, locations and schedules.</h2></div><div className="pct-delivery-grid"><article><b>01</b><h3>In-house</h3><p>Bring focused, instructor-led learning directly to your organisation and team.</p></article><article><b>02</b><h3>ETI classroom</h3><p>Give learners a dedicated professional environment away from day-to-day demands.</p></article><article><b>03</b><h3>Live online</h3><p>Reach distributed teams through interactive virtual facilitation.</p></article><article><b>04</b><h3>Blended</h3><p>Combine face-to-face and digital learning around your audience and objectives.</p></article></div></section>
    <section className="pct-section pct-faq"><div className="pct-section-head"><span>Plan with confidence</span><h2>What L&amp;D and compliance leaders ask before they engage.</h2></div><div>{faqs.map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
    <section className="pct-final"><div><span>Bring us your AML &amp; compliance learning brief</span><h2>Have a compliance capability priority on your agenda?</h2><p>Share your training requirement, organisation or industry, target audience, relevant programme, desired learning outcome and business requirement.</p><div><a href="https://wa.me/971544177480?text=Hi%2C%20I%20want%20to%20discuss%20customised%20corporate%20training" target="_blank" rel="noopener noreferrer">+971 544 177480</a><a href="https://wa.me/971545353558?text=Hi%2C%20I%20want%20to%20discuss%20customised%20corporate%20training" target="_blank" rel="noopener noreferrer">+971 545 353 558</a><a href="mailto:courses@entrepot.ae">courses@entrepot.ae</a></div></div><LeadForm/></section>
    <section className="pct-addresses"><div className="pct-addresses-head"><span>Speak with our corporate learning team</span><h2>Turn your next training request into a stronger brief.</h2><p>Email, call or WhatsApp ETI to discuss the audience, capability gap and outcome you need to address.</p><a href="mailto:courses@entrepot.ae"><MailIcon/><span>courses@entrepot.ae</span></a></div><div className="pct-office-grid"><article><span>01 / United Arab Emirates</span><h3>Dubai Office</h3><address>109, First Floor, Al Bannai Building,<br/>Plot No. 47, Al Nahda First,<br/>Dubai, United Arab Emirates</address><div><a href="https://wa.me/971544177480?text=Hi%2C%20I%20want%20to%20discuss%20customised%20corporate%20training" target="_blank" rel="noopener noreferrer"><WhatsAppIcon/>+971 544 177480</a><a href="https://wa.me/971545353558?text=Hi%2C%20I%20want%20to%20discuss%20customised%20corporate%20training" target="_blank" rel="noopener noreferrer"><WhatsAppIcon/>+971 545 353 558</a><a href="tel:+97143423009">Landline: 04 342 3009</a></div><a className="pct-map-link" href="https://www.google.com/maps/search/?api=1&query=Al%20Bannai%20Building%20Al%20Nahda%20First%20Dubai" target="_blank" rel="noopener noreferrer">View on Google Maps ↗</a></article><article><span>02 / India</span><h3>Mumbai Office</h3><address>910, 9th Floor, Hub Town Viva,<br/>Shankarwadi, Western Express Highway,<br/>Jogeshwari East, Mumbai 400 060</address><div><a href="tel:+919920656666">+91 99206 56666</a></div><a className="pct-map-link" href="https://www.google.com/maps/search/?api=1&query=Hubtown%20Viva%20Jogeshwari%20East%20Mumbai%20400060" target="_blank" rel="noopener noreferrer">View on Google Maps ↗</a></article></div></section>
    <footer className="pct-footer"><img src="/entrepot-logo-transparent.png" alt="Entrepôt Training Institute"/><div className="pct-footer-details"><div className="pct-footer-contact"><span>Dubai · Mumbai</span><a href="https://wa.me/971544177480?text=Hi%2C%20I%20want%20to%20discuss%20customised%20corporate%20training" target="_blank" rel="noopener noreferrer" aria-label="WhatsApp +971 544 177480"><WhatsAppIcon/>+971 544 177480</a><a href="https://wa.me/971545353558?text=Hi%2C%20I%20want%20to%20discuss%20customised%20corporate%20training" target="_blank" rel="noopener noreferrer" aria-label="WhatsApp +971 545 353 558"><WhatsAppIcon/>+971 545 353 558</a><a href="mailto:programs@entrepot.ae"><MailIcon/>programs@entrepot.ae</a></div><nav className="pct-socials" aria-label="Entrepôt social media">{socialLinks.map(([name,url])=><a href={url} target="_blank" rel="noopener noreferrer" aria-label={`Visit ETI on ${name}`} key={name}><SocialIcon name={name}/><span>{name}</span></a>)}</nav><span>© 2026 Entrepôt Training Institute</span></div></footer>
    <nav className="pct-mobile-contact" aria-label="Quick contact"><a href={CORPORATE_CONTACT.whatsapp} aria-label="WhatsApp ETI">WhatsApp</a><a href={CORPORATE_CONTACT.phone} aria-label="Call ETI">Call</a><a href={CORPORATE_CONTACT.email} aria-label="Email ETI">Email</a></nav>
  </main>
}
