import {SiteFooter,SiteHeader} from "../components";

const themes=[
  {no:"01",title:"Practical from day one",text:"Learning is designed around workplace decisions, realistic challenges and tools participants can apply immediately.",area:"Applied learning"},
  {no:"02",title:"Expertise made clear",text:"Complex professional frameworks are translated into focused explanations, useful discussion and confident practice.",area:"Facilitation"},
  {no:"03",title:"Confidence that lasts",text:"Participants leave with greater clarity, stronger professional judgement and a clear plan for continued development.",area:"Learner growth"},
  {no:"04",title:"Relevant to the business",text:"Corporate programmes connect capability building to organisational priorities, roles and measurable outcomes.",area:"Business impact"}
];

export default function Testimonials(){return <main><SiteHeader/><section className="testimonials-hero"><div className="testimonials-hero-image"/><div className="testimonials-hero-copy"><div className="section-kicker light">Learner Perspectives</div><h1>Experiences that<br/><em>move people forward.</em></h1><p>What participants and organisations value about learning with Entrepôt.</p></div></section><section className="testimonials-intro section-pad"><div><div className="section-kicker">Feedback themes</div><h2>Learning people can<br/>use and remember.</h2></div><div><p className="lead">The most meaningful feedback is reflected in what learners do differently after a programme.</p><p>These themes represent the qualities participants consistently seek from professional development: practical relevance, credible expertise, greater confidence and visible workplace value.</p></div></section><section className="testimonial-grid section-pad">{themes.map(t=><article key={t.no}><div><span>{t.no}</span><small>{t.area}</small></div><h2>{t.title}</h2><p>{t.text}</p></article>)}</section><section className="testimonial-note"><div><span>Approved learner stories</span><h2>Share your Entrepôt experience.</h2></div><div><p>Completed a programme with us? We welcome thoughtful feedback that can help future learners make an informed choice.</p><a className="btn-gold" href="mailto:courses@entrepot.ae?subject=My Entrepot Learning Experience">Email courses@entrepot.ae <span>↗</span></a></div></section><SiteFooter/></main>}
